from loguru import logger

paom_date_format = '%Y-%m-%d'
paom_date_format_tb = '%d.%m.%Y'

DATASET="PAOM"
PAOM_TABLE="PAOM_Data" 
PAOM_TABLE_ASIS="PAOM_Data_ASIS" 
DATASET_LOCATION="EU"
RECORDS_LIMIT=5000 
MASTER_DATASET='masterData'
RU_DATA_BUCKET="paom-bucket-archive"
ALLOWED_EMAIL_DOMAINS="ikea.com,ingka.ikea.com,ingka.com"
OFFBOARDING_LIST_VIEW="offboarding_list_data_view"
COUNTRIES_FOR_DEPTNAME_WITH_CODE="PL"
country_list = COUNTRIES_FOR_DEPTNAME_WITH_CODE.split(',')
MISSING_KEY_ATT_DATA="Missing_Key_Att_Data"

# Here all methods should be defineds
org_unit_mapping =  {
                    'GF00006' : ['Group Functions','Group Global Operations'],
                    'IC00001' : ['Ingka Centres','Ingka Centres'],
                    'GF00010' : ['Group Functions','Group People & Culture'],
                    'GF00001' : ['Group Functions','Group Business Steering'],
                    'GF00011' : ['Group Functions','Group Procurement'],
                    'GF00009' : ['Group Functions','Group Finance'],
                    'II00001' : ['Ingka Investments','Ingka Investments'],
                    'GF00007' : ['Group Functions','Group Real Estate'],
                    'GF00008' : ['Group Functions','Group Digital'],
                    'RF00001' : ['Retail Support Functions','Customer Fulfilment'],
                    'RF00002' : ['Retail Support Functions','Market Support'],
                    'IR00001' : ['Retail Support Functions','Retail Management']
                    }

poam_drop_cols_l = ['addresses',
                    'annualWorkingHours',
                    'birthPlace',
                    # 'businessUnit',
                    # 'businessUnitType',
                    # 'cdsCreateTimeStamp',
                    'cdsUpdateTimeStamp',
                    # 'chosenFirstName',
                    'chosenFullName',
                    'companyRegion',
                    'contractEndDate',
                    'contractStartDate',
                    # 'contractType',
                    # 'costDistributions',
                    # 'countryKey',
                    'dailyWorkingHours',
                    # 'dateOfBirth',
                    # 'departmentCode',
                    # 'departmentName',
                    # 'emailId',
                    # 'employeeGroup',
                    # 'employeeId',
                    # 'employeeSubGroup',
                    # 'employmentPercentage',
                    # 'employmentStatus',
                    # 'employmentType',
                    # 'gender',
                    'guid',
                    # 'gvCompanyCode',
                    # 'hireDate',
                    # 'homeSite',
                    'hoursPerWeek',
                    'ikeaPhoneNumber',
                    'initials',
                    # 'job',
                    # 'jobTitle',
                    # 'language',
                    # 'legalFirstName',
                    'legalFullName',
                    # 'legalLastName',
                    'legalMiddleName',
                    # 'managerEmployeeId',
                    # 'managerFlag',
                    'mobileNumber',
                    'monthlyHours',
                    'nationality',
                    'networkId',
                    # 'orgUnitAbbreviation',
                    # 'organizationalKey',
                    'partTimeIndicator',
                    'personId',
                    # 'personalArea',
                    # 'personalAreaName',
                    # 'personalSubArea',
                    # 'personalSubAreaName',
                    'position',
                    'positionName',
                    'roleList',
                    'startInPosition',
                    # 'terminationDate',
                    'uid',
                    'weeklyWorkdays']

mapping_dict = {'employeeId': 'EmployeeId',  
                'legalFirstName': 'FirstName',  
                'legalLastName': 'LastName',  
                'chosenFirstName': 'chosenFirstName',  
                'jobTitle': 'JobTitle',  
                'job': 'JobCode',  
                'gender': 'Gender',  
                'dateOfBirth': 'BirthDate',  
                'employmentPercentage': 'ContractType',  
                'firstDayAtIKEA': 'StartDateInIngka',  
                'personalSubArea': 'EmploymentGroupCode',  
                'employmentStatus': 'EmploymentStatus',  
                'employeeGroup': 'EmploymentGroupName',  
                'employeeSubGroup': 'SubEmploymentGroupCode',  
                'SubEmploymentGroupName': 'SubEmploymentGroupName',  
                'emailId': 'EmailAddress',  
                'countryKey': 'Country',  
                'Business_Area': 'Business_Area',  
                'companyName': 'CompanyName',  
                'gvCompanyCode': 'CompanyCode',  
                'businessUnitType': 'BusinessUnitType',  
                'businessUnit': 'BusinessUnitCode', 
                'BusinessUnitName': 'BusinessUnitName', 
                'personalSubAreaName': 'Function',  
                'departmentCode': 'OrgUnitCode', 
                'departmentName': 'DepartmentName', 
                'SubDepartment': 'SubDepartment', 
                'costCentre': 'CostCentre', 
                'orgUnitAbbreviation': 'orgUnitAbbreviation',
                'managerFlag': 'ManagerFlag', 
                'language': 'PreferedLanguage', 
                'managerEmployeeId': 'ManagerEmployeeId', 
                'ManagerFirstName': 'ManagerFirstName', 
                'ManagerLastName': 'ManagerLastName',  
                'ManagerEmailAddress': 'ManagerEmailAddress', 
                'Age': 'Age',  
                'CostCentreFull': 'CostCentreFull',
                'AgeGroup': 'AgeGroup',  
                'Tenure': 'Tenure', 
                'TenureGroup': 'TenureGroup', 
                'isCountryRetailManager': 'isCountryRetailManager',  
                'DataSource': 'DataSource', 
                'cdsCreateTimeStamp': 'CDSCreateDate', 
                'organizationUnit':'OrganizationUnit',
                'organizationUnitCode':'OrganizationUnitCode', 
                'organizationUnitName':'OrganizationUnitName', 
                'organizationUnitType':'OrganizationUnitType',
                'personalArea': 'PersonalArea',
                'subDepartmentName':'SubDepartmentName', 
                'divisionName':'DivisionName', 
                'division':'Division',
                'BusinessUnit':'BusinessUnit'
                }

org_unit_abbreviations = {
    'C_BS': ('Group Functions', 'CFO - Business Steering'),
    'C_BS_BD': ('Group Functions', 'CFO - Business Steering'),
    'C_BS_GB': ('Group Functions', 'CFO - Business Steering'),
    'C_BS_MS_E2E': ('Group Functions', 'CFO - Business Steering'),
    'C_BS_RO': ('Group Functions', 'CFO - Business Steering'),
    'C_BS_VC&I': ('Group Functions', 'CFO - Business Steering'),
    'C_COMM': ('Group Functions', 'Group Communication'),
    'C_DIGI': ('Group Functions', 'Group Digital'),
    'C_DIGITMA': ('Group Functions', 'Group Digital'),
    'C_FIN': ('Group Functions', 'CFO - Group Finance'),
    'C_GO': ('Group Functions', 'CFO - Global Operations'),
    'C_L&G': ('Group Functions', 'CFO - Group Legal & Governance'),
    'C_MGMT': ('Group Functions', 'Ingka Management'),
    'C_P&C': ('Group Functions', 'Group People & Culture'),
    'C_PROC': ('Group Functions', 'CFO - Group Procurement'),
    'C_R&C': ('Group Functions', 'CFO - Business Risk & Compliance'),
    'C_REAL': ('Group Functions', 'CFO - Group Real Estate'),
    'C_SD&I': ('Group Functions', 'Group Strategy, Development, and Innovation'),
    'C_SUST': ('Group Functions', 'CFO - Group Sustainability'),
    'IC_SUST': ('Ingka Centres', 'IC - Sustainability'),
    'IC_C&D': ('Ingka Centres', 'IC - Commercial & Digital'),
    'IC_CENTRES': ('Ingka Centres', 'IC - Management'),
    'IC_CFO': ('Ingka Centres', 'IC - CFO'),
    'IC_COMMS': ('Ingka Centres', 'IC - Communications'),
    'IC_E&D': ('Ingka Centres', 'IC - Expansion & Development'),
    'IC_MP': ('Ingka Centres', 'IC - Operations Meeting Place'),
    'IC_OPS': ('Ingka Centres', 'IC - Operations Service Office'),
    'IC_P&C': ('Ingka Centres', 'IC - People & Culture'),
    'NL_AMSHULT': ('Group Functions', 'CFO - Global Support'),
    'NL_LEIDEN': ('Group Functions', 'CFO - Global Support'),
    'SE_HUBHULT': ('Group Functions', 'CFO - Global Support'),
    'R_CFF': ('Retail Support Functions', 'Customer Fulfilment'),
    'R_EXP': ('Retail Support Functions', 'Expansion'),
    'R_MS': ('Retail Support Functions', 'Market Support'),
    'R_OTHER': ('Retail Support Functions', 'Other'),
    'R_RETAIL': ('Retail Support Functions', 'Retail Management'),
    'C_INVESTMENT': ('Ingka Investments', 'Ingka Investments'),
    'EE_1083': ('Ingka Investments', 'Ingka Investments'),
    'LT_1086': ('Ingka Investments', 'Ingka Investments'),
    'LV_1085': ('Ingka Investments', 'Ingka Investments'),
    'RO_1079': ('Ingka Investments', 'Ingka Investments'),
    'RO_1082': ('Ingka Investments', 'Ingka Investments'),
    'RO_1084': ('Ingka Investments', 'Ingka Investments'),
}

business_unit_type_mappings = {
    'STO': 'Store',
    'CSC': 'Customer Service Centre',
    'SO': 'Service Office',
    'ITO': 'IT Office',
    'DT': 'Distribution Centre',
    'DT3': 'Distribution Centre',
    'CDC': 'Customer Distribution Centre',
    'BSU': 'Business Support Unit',
    'PSU': 'Property Support Unit',
    'SHC': 'Shopping Centre',
    'BSC': 'Business Service Centre',
    'DSU': 'Distribution Support Unit',
    'IMS': 'IMS Office',
    'PCU': 'Property Cluster Unit',
    'CFF': 'Distribution Support Unit',
    'DSO': 'Distribution Service Office',
    'OFB': 'Office Building',
    'TSO': 'Trading Service Office',
    'FR7': 'Franchisor',
    'FR': 'Franchisor',
    'SUP': 'Supplier',
    'CSO': 'Centres Service Office',
    'ORB': 'Office and Residential Building',
    'DCC': 'Distribution Centre Components',
    'AIR': 'Airport',
    'CAR': 'Carrier',
    'CMP': 'Customer Meeting Point',
    'COM': 'Company',
    'CP': 'Consolidation Point',
    'DTI': 'Distribution Centre IMS',
    'EQL': 'Equipment Re-loading',
    'ESP': 'External Service Provider',
    'FCT': 'Factory',
    'FDC': 'Food Distribution Centre',
    'FOR': 'Forestry',
    'FSU': 'Food Supplier',
    'HOT': 'Hotel',
    'ICS': 'IKEA Component Supplier',
    'IMT': 'Intermodal Terminal',
    'ISV': 'Indirect Material and Service Vendor',
    'ITP': 'Internal Transit Point',
    'LAB': 'Laboratory',
    'LND': 'Land',
    'LSC': 'Local Service Centre',
    'MUS': 'Museum',
    'PPP': 'Pallet Purchase Point',
    'PPT': 'Pallet Platform',
    'PRC': 'Pallet Recycling Point',
    'PRP': 'Pallet Repair Point',
    'PRT': 'Port',
    'PSP': 'Pallet Sales Point',
    'QSC': 'Quality Support Centre',
    'REI': 'Real Estate Investment',
    'RGR': 'Retail Goods in Transit Receiver',
    'RMS': 'Raw Material Supplier',
    'RUP': 'Responsible Unit for Development/Maintain Products',
    'SCP': 'Pallet Scrapping Account',
    'SSC': 'Shared Service Centre',
    'SUP': 'Supplier',
    'TA': 'Trading Agent',
    'WDF': 'Windfarm',
}

common_PAOM_cols_l = list(mapping_dict.values())
